### ISSUE TITLE
Fails with "Failed to bind to address." on Linux / .Net 6

### ISSUE THREAD

**Issue by JKirk865** [derek-will/SocketCANSharp#40]
I pulled the project to compare the performance of you library with the Iot.Device.SocketCAN. I can't seem to open the interface on "can0" but I know its valid and has data coming across. I tried integrating your project into mine AND running your stand-along Sniff program (changing vcan0 for can0). Same error both ways... I'm running as root, nothing else has the interface open. Linux is an in-house Yocto distribution.

I can enumerate the interfaces (var canList = CanNetworkInterface.GetAllInterfaces(true);)

```
var can = CanNetworkInterface.GetAllInterfaces(true).First(iface => iface.Name.Equals("can0"));    
using (var rawCanSocket = new RawCanSocket())    
{   
rawCanSocket.Bind(can);  /* BOMBs here...*/    
```

It's probably something dumb I'm doing.. Also maybe upgrade from .Net 5 to .Net 6 now that's its deprecated.

**Comment by derek-will** [comment]
Hi @JKirk865 - Thanks for reaching out. 

Can you pull the errno by either invoking `LibcNativeMethods.Errno` or catching the `SocketCanException` and inspecting the `NativeErrorCode` property?

**Comment by derek-will** [comment]
Just a quick follow up - I made a sample project, pulled down the latest version of SocketCANSharp (0.7.0), wrote a simple program, and built it against .NET 6. Ran it and everything worked perfectly so .NET 6 appears to not be the problem here. 

**Note:** SocketCANSharp 0.7.0 changed build target from .NET 5 to .NET Standard 2.0 to match the best practices guidelines.

**Comment by JKirk865** [comment]
I'll add a line or two and snag the errno. I also need to verify I have the libraries you are expecting to p/invoke in this stripped down Yocto build.  Can you comment on any performance comparison you have already done? Can you describe your test system? Arm32/64 vs Intel? Ubuntu, nVidia, ? CAN interface USB or integrated Hardware? (I'm also open to moving this conversation to email, can share more,  .. seems weird to talk here) my email is on my public profile.

**Comment by derek-will** [comment]
Hi @JKirk865,

The wrapper only P/Invokes the libc library. Are you having success with using the `Iot.Device.SocketCan` wrapper solution? 

Quick Q&A:

> Can you comment on any performance comparison you have already done? 

I have never done a performance comparison against any other .NET SocketCAN library. From what I have seen, I believe that this library offers superior feature coverage. In terms of raw performance, I've tested the library by writing a simple bus sniffer which read from a loaded CAN bus and it was able to read from the queue without dropping frames or having any noticeable lag.

I also have 328 current unit tests covering various success and error conditions.

> Can you describe your test system? 

**Operating System:** Ubuntu 20.04.4 LTS
**Kernel:** Linux 5.17.5-76051705-generic
**Architecture:** x86-64

> Arm32/64 vs Intel?

Intel Core i5

> CAN interface USB or integrated Hardware?

USB2CAN for physical testing and vcan for virtual testing.

I am definitely open to moving the conversation to email as well - Just want to gather as much "generic" information here as possible as it may be useful to a future user with a similar issue. Thanks again for your interest in the project.

**Comment by JKirk865** [comment]
Yes the "Iot.Device.SocketCan" option is working well for reading Raw CAN packets (8-byte) from a XSENS IMU. Reading a little more than 550 msgs per second. But, the CPU load is significant on my little ARM32 i.MX6UL, not leaving much more processing power for "other" activities.  I started looking at this in case it offered improved CPU performance.  I've already examined the "Iot.Device.SocketCan" and am not seeing any obvious improvements.   My Linux kernel is 4.9.280 and the CAN hardware attached directly to the processor, bitrate is 500k.

The Bind is returning -1, not sure where else to go for the errno?

Code in Question
```
       public void Bind(SockAddrCan addr)
        {
            if (_disposed)
                throw new ObjectDisposedException(GetType().FullName);

            if (addr == null)
                throw new ArgumentNullException(nameof(addr));

            int result = LibcNativeMethods.Bind(SafeHandle, addr, Marshal.SizeOf(typeof(SockAddrCan)));
            if (result != 0)
            {
                var e = String.Format("Unable to assign the provided SocketCAN raw address to the underlying CAN_RAW Socket. Result:{0}", result);
                Logging.WriteError(e);
                **throw new SocketCanException(
                    String.Format("Unable to assign the provided SocketCAN raw address to the underlying CAN_RAW Socket. Result:{0}", result)
                );**
            }

            IsBound = true;
        }
```
Output
```
2022-08-24 18:03:50.3973 ERROR Unable to assign the provided SocketCAN raw address to the underlying CAN_RAW Socket. Result:-1|
Unhandled exception. SocketCANSharp.Network.SocketCanException (0x80004005): Success
   at SocketCANSharp.Network.RawCanSocket.Bind(SockAddrCan addr) in /home/root/dev/cstarapp/SocketCANSharp/Network/RawCanSocket.cs:line 182
   at SocketCANSharp.Network.RawCanSocket.Bind(CanNetworkInterface iface) in /home/root/dev/cstarapp/SocketCANSharp/Network/RawCanSocket.cs:line 200
   at CStarApp.imuCarBodySensor.CollectSamples_xsens(Object obj) in /home/root/dev/cstarapp/CStarApp/imuCarBodySensor.cs:line 208
   at System.Threading.Thread.StartCallback()
```

The GetAllInterfaces returns this and I am passing on "can0"
```
2022-08-24 17:59:01.2150 imuCarBodySensor 18 INFO CanNetworkInterface: Index: 4; Name: can0; Is Virtual: False|
2022-08-24 17:59:01.2190 imuCarBodySensor 18 INFO CanNetworkInterface: Index: 5; Name: can1; Is Virtual: False|

var can = CanNetworkInterface.GetAllInterfaces(true).First(iface => iface.Name.Equals("can0"));
````

**Comment by derek-will** [comment]
Hi @JKirk865,

I haven't tested my bindings on a 32-bit system yet. I do have a RPi2 v1.1 which is ARM32. I will test on that and see what I find.

In regards to your question:

> The Bind is returning -1, not sure where else to go for the errno?

**Option 1 - Try/Catch and Print NativeErrorCode**

```
using (var rawCanSocket = new RawCanSocket())    
{
    try
    {
        rawCanSocket.Bind(can);
    }
    catch (SocketCanException ex)
    {
        Console.WriteLine($"NativeErrorCode: {ex.NativeErrorCode}");
    }
}
```

**Option 2 - Try/Catch and Print Errno**

```
using (var rawCanSocket = new RawCanSocket())    
{
    try
    {
        rawCanSocket.Bind(can);
    }
    catch (SocketCanException)
    {
        Console.WriteLine($"Errno: {LibcNativeMethods.Errno}");
    }
}
```
Please let me know what you find. Thanks!

**Comment by JKirk865** [comment]
Thanks for the pointer on catching errno.. I'll give that a try.. Maybe a day or so until I am back near that hardware again..

**Comment by JKirk865** [comment]
Its errno 22 which appears to be "Invalid argument" not sure if that's super helpful though,

**Comment by derek-will** [comment]
Quick update. I set up an ARM32 device with Kernel 4.9 and .NET. I am able to reproduce the error. I hope to zero in on the issue soon.

**Comment by derek-will** [comment]
I have identifed the fix. The bug had to do with how I was marshalling the union in the `sockaddr_can` struct - My approach was alright on x64, but broke on ARM32. 

I will work to have a fix out within the next week. In the future, all releases will be tested on my ARM32 test device and I will also set up an ARM64 device as well for testing thoroughness. I should probably get to a point of testing the Alpine runtime variants as well.

**Comment by derek-will** [comment]
Having some more time to look into the issue - The problem is based on the version of kernel being used and actually has nothing to do with the architecture or runtime.

In the more recent kernels:

```
static int raw_bind(struct socket *sock, struct sockaddr *uaddr, int len)
{
	struct sockaddr_can *addr = (struct sockaddr_can *)uaddr;
	struct sock *sk = sock->sk;
	struct raw_sock *ro = raw_sk(sk);
	int ifindex;
	int err = 0;
	int notify_enetdown = 0;

	if (len < RAW_MIN_NAMELEN)
		return -EINVAL;
// ...
}
```
However, in kernel 4.9:

```
static int raw_bind(struct socket *sock, struct sockaddr *uaddr, int len)
{
	struct sockaddr_can *addr = (struct sockaddr_can *)uaddr;
	struct sock *sk = sock->sk;
	struct raw_sock *ro = raw_sk(sk);
	int ifindex;
	int err = 0;
	int notify_enetdown = 0;

	if (len < sizeof(*addr))
		return -EINVAL;
// ...
}

```
The difference is that older kernels expect the `len` argument in the call to the `bind` function to be the largest possible size of the struct (what `sizeof` returns). The `sockaddr_can` struct is shared by Raw CAN, BCM, ISO-TP, and J1939 sockets and the relevant data in the struct depends on the socket type that is making use of it. In later versions of the kernel, the macro **CAN_REQUIRED_SIZE** is used to compute the required length (`RAW_MIN_NAMELEN`) and it sets the threshold to a smaller value as it only demands what is absolutely needed for the particular socket type. My managed type which only includes the relevant fields for Raw CAN is therefore acceptable to later versions, but not to older versions of the kernel.

I will add padding to the managed `sockaddr_can` type for Raw CAN in order to make it compatible with older versions of the kernel. I am including this change in the upcoming 0.8.0 release.

**Comment by JKirk865** [comment]
Wow.. Great sleuthing..

**Comment by derek-will** [comment]
Hi @JKirk865, just a quick update. I am doing thorough runtime testing of SocketCAN# and found some actual bugs when running in a 32-bit application. As a result, the 0.8.0 release is delayed a little bit.
