### ISSUE TITLE
Failing to "Sniff" J1939 Msgs

### ISSUE THREAD

**Issue by JKirk865** [derek-will/SocketCANSharp#60]
Derek,
  I successfully used the CANBusSniffer example to read RAW can msgs but have failed a few times at sniffing J1939 msgs.  Assuming its trivial, any chance you could add that example as well?  I have a device that is sending J1939 msgs, and I see CAN frames showing up  (via ifconfig can0).  And the "Raw" sniffer can see the data coming in. It must be a basic misunderstanding I have about J1939.. 

This is what I have.. the code should look pretty familiar.. 

```
using (var j1939Handle = LibcNativeMethods.Socket(SocketCanConstants.PF_CAN, SocketType.Dgram,
                                                                    SocketCanProtocolType.CAN_J1939))
                {
                    if (j1939Handle.IsInvalid)
                    {
                        log.Error("Failed to create socket.");
                        return;
                    }
                    var ifr = new Ifreq(can_interface);
                    int ioctlResult = LibcNativeMethods.Ioctl(j1939Handle, SocketCanConstants.SIOCGIFINDEX, ifr);
                    if (ioctlResult == -1)
                    {
                        log.Error("Failed to look up interface by name.");
                        return;
                    }

                    int value = 1;
                    int enableBroadcastResult = LibcNativeMethods.SetSockOpt(j1939Handle, SocketLevel.SOL_SOCKET, SocketLevelOptions.SO_BROADCAST, ref value, Marshal.SizeOf(typeof(int)));
                    if (enableBroadcastResult == -1)
                    {
                        log.Error("Failed to enable SO_BROADCAST option. {0}.", enableBroadcastResult);
                        return;
                    }

                    int prio = 3;
                    int prioResult = LibcNativeMethods.SetSockOpt(j1939Handle, SocketLevel.SOL_CAN_J1939, J1939SocketOptions.SO_J1939_SEND_PRIO, ref prio, Marshal.SizeOf(typeof(int)));
                    if (prioResult == -1)
                    {
                        log.Error("Failed setting SO_J1939_SEND_PRIO option. {0}.", prioResult);
                        return;
                    }

                    int frameSize = Marshal.SizeOf(typeof(CanFrame));
                    log.Debug("CollectSamples_CAN starting collection loop. frameSize:{0}", frameSize);

                    while (!stopCollecting)
                    {
                        var readFrame = new CanFrame();
                        int nReadBytes = LibcNativeMethods.Read(j1939Handle, ref readFrame, frameSize);
                        if (nReadBytes > 0)
                        {
                            log.Debug("CollectSamples_CAN adding frame to queue. nBytes:{0} qSize:{1}",
                                nReadBytes, concurrentQueue.Count);
                            concurrentQueue.Add(readFrame);
                        }
                    }
```

**Comment by JKirk865** [comment]
Am I possibly missing the j1939 promiscuous mode?

**Comment by derek-will** [comment]
Hi Jerry, I apologize for the delay. Work and home activities have kept me away longer than I would have liked. I am also working on adding Netlink socket support for reading out and possibly configuring the CAN network interface settings. That work is also an enabler for CAN_GW support. 

To the task at hand, a few quick points: 

1. When writing a packet sniffer, promiscuous mode is a very useful feature of J1939 sockets to leverage. I would advise using it here.
2. Use the read interface that takes in a raw byte array when reading from a J1939 socket. Reading by CAN frame structure is for Raw CAN sockets. You can also view the relevant unit tests for some examples. 

> public static extern int Read(SafeFileDescriptorHandle socketHandle, [Out] byte[] data, int dataSize);


3. Setting Priority level isn't going to get you anything as you are not transmitting messages out onto the CAN bus in this application.
4. Enabling Broadcast option also isn't going to get you anything as you are not transmitting. 

And yes, I can totally add an example application for sniffing a J1939 network. I will work on adding that example application after my Netlink socket work is at a good stopping point. I will close this ticket when I commit the example application code to this repo.

**Comment by JKirk865** [comment]
Thanks Dereck, I should have replied a few days ago, I think I figured out what you just said.. 
```
    byte[] canBuffer = new byte[128];
  
    var srcAddr = new SockAddrCanJ1939()
    {
        Name = SocketCanConstants.J1939_NO_NAME,
        PGN = SocketCanConstants.J1939_NO_PGN,
        Address = SocketCanConstants.J1939_NO_ADDR,
    };
    var addrSize = Marshal.SizeOf(typeof(SockAddrCanJ1939));
    var nReadBytes = LibcNativeMethods.RecvFrom(j1939Socket.SafeHandle, canBuffer, canBuffer.Length, MessageFlags.None, srcAddr, ref addrSize);
```

It might be handy to add some access methods to SockAddrCanJ1939 to decode the PGN further.. 
```
  var src = PGN & 0xff; // First byte, src addr "SA"
  var pdu_specific = (PGN & 0xff00) >> 8; // Second Byte, called "PS"
  var pdu_format = (PGN & 0xff0000) >> 16; // Third Byte called "PF"
  var misc = (PGN & 0xff000000) >> 24; // Fourth Byte
  var data_page = misc & 0x1;
  var reserved = (misc & 0x2) >> 1;
  var priority = (misc & 0x1c) >> 2;
```

I've also managed to hook all this to a DBC Parser (using https://github.com/EFeru/DbcParser for now) and decode the msgs from a log file. Next week or two I should be able to test this on a live truck.

I do expect to be transmitting in the future as well. Thanks again for your help and hard work going into this project.
