### ISSUE TITLE
Add utility methods for accessing basic standard information

### ISSUE THREAD

**Issue by derek-will** [derek-will/SocketCANSharp#62]
As suggested in Issue #60 - This would be helpful to users of the library to have some built-in utility methods to do common standardized tasks associated with these CAN sockets.

**Comment by JKirk865** [comment]
This sounds helpful, as a CAN neophyte there was some confusion about the proper names of things. A "PDU" is 29 bits, the PGN is 2 bytes made up of the PF and PS, and then there is a CAN_ID used in DTC files which looks like a PDU but isn't.    BTW, I've tested the latest J1939 code against and International truck and it's working great.
