### ISSUE TITLE
Used for Android?

### ISSUE THREAD

**Issue by yureng** [derek-will/SocketCANSharp#73]
Excuse me, should it also be used for Android?

**Comment by derek-will** [comment]
Hi @yureng, sorry for the delay. Last week was super hectic. Yes, I believe it is possible to use this library on Android, but I will have to test to be 100% certain. As luck should have it, I will be inheriting a Windows machine soon. I will install Visual Studio on it and build an Android Application in C# using SocketCAN# to verify that there are no issues.

**Comment by yureng** [comment]
@derek-will     Thank you very much for your reply !
