### ISSUE TITLE
Trying out IsoTP, Getting "Protocol not supported" exception

### ISSUE THREAD

**Issue by JKirk865** [derek-will/SocketCANSharp#78]
I've been asked to interface with an ISO-TP device and I was trying out the interface for the first time. I got this message using the example code with version 0.11.0 when I tried to transmit 3 bytes.

2023-11-07 14:20:51.9047 JBCANTransfer 1 WARN Ignoring SocketCANSharp.Network.SocketCanException TransmitBlock(). SocketCANSharp.Network.SocketCanException
   Exception Messages
[0] Protocol not supported
   Exception StackTraces
[0]    at SocketCANSharp.Network.IsoTpCanSocket..ctor()
   at SimpleLogger.JBCANTransfer.TransmitBlock(Byte[] data, UInt32 destination_id)

Is this my kernel possibly? or

**Comment by JKirk865** [comment]
Follow-up I was able to run the code on a RP4 / Raspbian system so this is probably not my code. Any advice on what to look for on the system that does not work? a Kernel option?

**Comment by JKirk865** [comment]
ok.. confirmed the system that did not work is Linux version 4.9.280.  I'm guess that's the problem eh?

**Comment by derek-will** [comment]
Hi @JKirk865, sorry I was unavailable for a few days there. Yes, ISO-TP sockets were added to the mainline kernel with the 5.10 release. You can build and load the kernel module on systems prior to the mainlining of the can-isotp module.

Source code and build instructions: https://github.com/hartkopp/can-isotp
