### ISSUE TITLE
Run on Windows OS?

### ISSUE THREAD

**Issue by liushanke** [derek-will/SocketCANSharp#80]
I run test the project on window.There is an error:DllNotFoundException: Unable to load DLL 'libc' or one of its dependencies.Otherwise,I want to kown if SocketCANSharp.dll can been used to CAN protocol port communication.

**Comment by liushanke** [comment]
I want to kown if SocketCANSharp.dll can been used to CAN protocol port communication on window OS.

**Comment by derek-will** [comment]
I will test within the next week to verify running conditions on Windows OS.

**Comment by derek-will** [comment]
Update: I have a Windows PC partially set up. Will provide verification soon.

**Comment by derek-will** [comment]
Yes, confirmed SocketCANSharp runs on Windows via WSL2. You will need to build and run your own custom kernel with CAN support enabled and then install dotnet in your WSL2 instance. It is not too difficult to do. I found a few tutorials/instructions online for enabling SocketCAN on WSL2 which is the only significant hurdle. I tested by running some of the example apps from this repo and they worked without issue. 

I will provide my instructions and update the main README to mention that you can run SocketCANSharp on Windows via WSL.
