### ISSUE TITLE
Question Regarding Can Message Time Stamps

### ISSUE THREAD

**Issue by ChaseGould** [derek-will/SocketCANSharp#86]
Is is possible call the ioctl time stamp request with this library? If not is there an alternative approach to getting time stamps for received can messages?

[socketCan docs](https://docs.kernel.org/networking/can.html) show it being called as:
struct timeval tv;
ioctl(s, SIOCGSTAMP, &tv);

**Comment by derek-will** [comment]
Hi @ChaseGould, I already have the `timeval` struct defined for Socket Level Options SO_SNDTIMEO and SO_RCVTIMEO. I will add support for leveraging via an `ioctl` call in the upcoming 0.12 release. It should be pretty easy to do so.

**Comment by derek-will** [comment]
@ChaseGould, I added initial support on the `develop` branch today. I am going to do some additional testing on ARM, x86, etc. and explore various potential "unhappy" paths. I will also update the CAN bus sniffer example application to include timestamps. I should have that done pretty soon and the 0.12 release will follow afterwards.

**Comment by ChaseGould** [comment]
Thank you @derek-will I appreciate it.
